const characters = [
    {
        "name": "Din Djarin",
        "species": "Human",
        "affiliation": "Mandalorian",
        "role": "Bounty Hunter",
        "weapon": "Amban Phase-Pulse Blaster",
        "homeworld": "Aquilae",
        "forceSensitive": false,
        "age": 35,
        "joinDate": "2020-11-12",
        "side": "Good"
    },
    {
        "name": "Grogu",
        "species": "Yoda's Species",
        "affiliation": "The Mandalorian",
        "role": "Foundling",
        "weapon": "None",
        "homeworld": "Unknown",
        "forceSensitive": true,
        "age": 50,
        "joinDate": "2020-11-12",
        "side": "Good"
    },
    {
        "name": "Cara Dune",
        "species": "Human",
        "affiliation": "New Republic",
        "role": "Former Shock Trooper",
        "weapon": "Heavy Blaster",
        "homeworld": "Alderaan",
        "forceSensitive": false,
        "age": 38,
        "joinDate": "2020-11-12",
        "side": "Good"
    },
    {
        "name": "Moff Gideon",
        "species": "Human",
        "affiliation": "Imperial Remnant",
        "role": "Leader",
        "weapon": "Darksaber",
        "homeworld": "Unknown",
        "forceSensitive": false,
        "age": 50,
        "joinDate": "2020-12-18",
        "side": "Evil"
    },
    {
        "name": "Bo-Katan Kryze",
        "species": "Human",
        "affiliation": "Mandalorian",
        "role": "Warrior",
        "weapon": "Blasters",
        "homeworld": "Mandalore",
        "forceSensitive": false,
        "age": 40,
        "joinDate": "2020-11-13",
        "side": "Good"
    },
    {
        "name": "Ahsoka Tano",
        "species": "Togruta",
        "affiliation": "Former Jedi",
        "role": "Force User",
        "weapon": "Dual Lightsabers",
        "homeworld": "Shili",
        "forceSensitive": true,
        "age": 45,
        "joinDate": "2020-12-18",
        "side": "Good"
    },
    {
        "name": "Fennec Shand",
        "species": "Human",
        "affiliation": "Boba Fett",
        "role": "Assassin",
        "weapon": "Sniper Rifle",
        "homeworld": "Unknown",
        "forceSensitive": false,
        "age": 40,
        "joinDate": "2020-12-18",
        "side": "Neutral"
    },
    {
        "name": "Boba Fett",
        "species": "Human (Clone)",
        "affiliation": "Bounty Hunter",
        "role": "Bounty Hunter",
        "weapon": "Blaster",
        "homeworld": "Kamino",
        "forceSensitive": false,
        "age": 41,
        "joinDate": "2020-12-18",
        "side": "Neutral"
    },
    {
        "name": "Mayfeld",
        "species": "Human",
        "affiliation": "None",
        "role": "Mercenary",
        "weapon": "Blaster",
        "homeworld": "Unknown",
        "forceSensitive": false,
        "age": 42,
        "joinDate": "2020-11-20",
        "side": "Neutral"
    },
    {
        "name": "Greef Karga",
        "species": "Human",
        "affiliation": "Bounty Hunters' Guild",
        "role": "Magistrate",
        "weapon": "Blaster",
        "homeworld": "Unknown",
        "forceSensitive": false,
        "age": 55,
        "joinDate": "2020-11-12",
        "side": "Good"
    },
    {
        "name": "Kuiil",
        "species": "Ugnaught",
        "affiliation": "None",
        "role": "Former Slave",
        "weapon": "None",
        "homeworld": "Arvala-7",
        "forceSensitive": false,
        "age": 60,
        "joinDate": "2020-11-12",
        "side": "Good"
    },
    {
        "name": "IG-11",
        "species": "Droid",
        "affiliation": "None",
        "role": "Nurse Droid",
        "weapon": "Blasters",
        "homeworld": "Unknown",
        "forceSensitive": false,
        "age": 5,
        "joinDate": "2020-11-12",
        "side": "Good"
    },
    {
        "name": "Cad Bane",
        "species": "Duros",
        "affiliation": "Bounty Hunter",
        "role": "Bounty Hunter",
        "weapon": "Blasters",
        "homeworld": "Duro",
        "forceSensitive": false,
        "age": 60,
        "joinDate": "2008-10-03",
        "side": "Evil"
    }
]
